package com.clientcrew.entity;

public enum ActivityType {
	
	
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,
    CUSTOMER_DELETED,

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,

    TASK_CREATED,
    TASK_UPDATED,
    TASK_STATUS_CHANGED,
    TASK_DELETED,

    USER_REGISTERED,
    USER_LOGIN,
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,

    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_DELETED,
    TEAM_UPDATED,

    PROFILE_UPDATED,
    PASSWORD_CHANGED,

    SETTINGS_UPDATED,

    MESSAGE_SENT,

    NOTIFICATION_READ
}